name             'ruby1.9.3'
maintainer       'Josh Rendek'
maintainer_email 'josh@joshrendek.com'
license          'All rights reserved'
description      'Installs/Configures ruby1.9.3'
version          '0.1.0'
